; PlatformIO Project Configuration File - Rotator7
; Mini Satellite-Antenna Rotator - Arduino Nano

[platformio]
src_dir = .

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
build_src_filter = +<*.cpp>
monitor_speed = 9600
build_flags = -I${PROJECT_DIR}
